---
#- name: "Test if SCL installed"
#  command: rpm -q centos-release-scl
#  register: scl_check
#  ignore_warnings: True

#- debug: msg="{{ scl_check }}"

- name: "Install git 2.18 profile.d script for SCL"
  copy: 
    src: profile-d-git-scl.sh
    dest: /etc/profile.d/git-scl.sh
    owner: root
    group: root
    mode: 0600
    backup: yes
  become: yes
  tags:
    - scl
  #when: scl_check.rc == 1
  
