---

- include: var_dump.yml
  when: lab_save_facts

- include: check_node.yml

- include: yum_update.yml
  when: lab_update 
 
- vars:
    local_packages: "{{ baseline_packages }}"
  include: yum_install.yml
  when: lab_baseline_packages
 
- include: repos.yml
  when: lab_base_repos

- include: git.yml
  when: lab_base_git

# consider putting this in the baseline packages, for now it serves as an example
- include: tmux.yml
  when: lab_base_tmux

- include: modulefiles.yml

- include: banner.yml
  when: lab_banner 

- include: harden_ssh.yml
  when: lab_harden_ssh

- include: node_exporter.yml
  when: lab_pne


