---

- include_var: epel.yml

- name: "Enable dnf PowerToolsi"
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
    mode: "0644"
  #notify:
  #  - yum update cache
  when: ansible_distribution_major_version == "8"

- name: "Install EPEL yum repos"
  yum:
    name: 
      - epel-release
    state: latest
  register: epel_repo
  become: true
        
- debug: msg="{{ epel_repo }}"

- name: "Install SCL yum repos"
  yum:
    name: 
      - centos-release-scl 
    state: latest
  register: scll_repo
  when: ansible_distribution_major_version != "8"

- debug: msg="{{ scl_repo}}"
  when: scl_repo is defined


