---
- name: "Install EPEL yum repos"
  yum:
    name: 
      - epel-release
    state: latest
  register: epel_repo
  become: true
        
- debug: msg="{{ epel_repo }}"

- name: "Install SCL yum repos"
  yum:
    name: 
      - centos-release-scl 
    state: latest
  register: scll_repo
  become: true
  when: ansible_distribution_major_version != "8"

- debug: msg="{{ scl_repo}}"
  when: scl_repo is defined
