---

- name: Packages to be installed 
  debug:
    msg: "Packages to be installed {{ local_packages }}"

- name: Install  packages (Version 6 or 7)
  yum: 
    name: "{{ local_packages }}"
    state: latest
    skip_broken: yes
    update_cache: yes
  ignore_errors: yes
  register: yum_cmd_out
  when:
    - (ansible_facts['distribution_major_version'] == '6') or
      (ansible_facts['distribution_major_version'] == '7')

- name: Install baseline packages (Version 8)
  dnf: 
    name: "{{ local_packages }}"
    state: latest
    skip_broken: yes
    update_cache: yes
  ignore_errors: yes
  register: yum_cmd_out
  when:
    - ansible_facts['distribution_major_version'] == '8'

- name: Print errors if yum failed
  debug:
    msg: "{{ yum_cmd_out }}"
  when: yum_cmd_out

