---
# handlers file 

########################################################################
# SSHD

- name: "(Handler: All Linux/Unix OSs) Restart sshd"
  service:
    name: "{{ sshd_service }}"
    state: restarted

########################################################################
# Prometheus Node Exporter

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted 

#######################################################################
# handlers file for ansible-freeipa-client
#
- name: restart sssd
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=sssd
    state=restarted




- name: restart ssh
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=ssh
    state=restarted


- name: reload systemd
  systemd:
    name: systemd
    daemon_reload: true

- name: reload service firewalld
  systemd:
    name: firewalld
    daemon_reload: true
    state: reloaded
